module.exports = {
  CHECK_VARIABLE: 'CHECK_VARIABLE',
  HTTP_REQUEST: 'HTTP_REQUEST',
  PROMPTING: 'PROMPTING',
  REPLACE_ACTION: 'REPLACE_ACTION',
  SEND_TEXT: 'SEND_TEXT',
  SET_LANGUAGE: 'SET_LANGUAGE',
  SET_DATA: 'SET_DATA',
  SUB_FLOW: 'SUB_FLOW',
};
